# Generated by Django 4.1.6 on 2023-03-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='audio_questions_and_solutions',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='constructive_questions_and_solutions',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='exams_collection',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='mcq_questions_and_answers',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='test_result',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_id',
            new_name='id',
        ),
    ]
