# Generated by Django 4.1.6 on 2023-03-09 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_rename_id_audio_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QUESTIONS_AND_ANSWERS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Ordinal', models.IntegerField()),
                ('Question', models.TextField()),
                ('Correct_answer', models.CharField(max_length=1)),
                ('Answer_a', models.TextField()),
                ('Answer_b', models.TextField()),
                ('Answer_c', models.TextField()),
                ('Answer_d', models.TextField()),
                ('Solution', models.TextField()),
                ('Split_content', models.BooleanField(default=True)),
                ('Is_MCQ', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.exams_collection')),
            ],
        ),
        migrations.RemoveField(
            model_name='mcq_questions_and_answers',
            name='exam',
        ),
        migrations.DeleteModel(
            name='CONSTRUCTIVE_QUESTIONS_AND_SOLUTIONS',
        ),
        migrations.DeleteModel(
            name='MCQ_QUESTIONS_AND_ANSWERS',
        ),
    ]
