# Generated by Django 4.1.6 on 2023-03-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_questions_and_answers_split_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions_and_answers',
            name='Answer_a',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='questions_and_answers',
            name='Answer_b',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='questions_and_answers',
            name='Answer_c',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='questions_and_answers',
            name='Answer_d',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='questions_and_answers',
            name='Correct_answer',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='questions_and_answers',
            name='Solution',
            field=models.TextField(null=True),
        ),
    ]
