# Generated by Django 4.1.6 on 2023-03-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_alter_questions_and_answers_answer_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams_collection',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exams_collection',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
