# Generated by Django 4.1.6 on 2023-03-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_exams_collection_duration_exams_collection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams_collection',
            name='image',
            field=models.FileField(default=None, upload_to='images/'),
        ),
    ]
