# Generated by Django 4.1.6 on 2023-03-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_exams_collection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(blank=True, max_length=200),
        ),
    ]
