# Generated by Django 4.1.6 on 2023-03-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHARED_USERS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Shared_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shared_user_id', to='src.user')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_id', to='src.user')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.exams_collection')),
            ],
        ),
    ]
