# Generated by Django 4.1.6 on 2023-03-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_shared_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Avatar',
            field=models.TextField(default=None),
        ),
    ]
