# Generated by Django 4.1.6 on 2023-04-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_user_avatar'),
        ('src', '0014_alter_test_result_specific_ordinal_and_more'),
    ]

    operations = [
    ]
