# Generated by Django 4.1.6 on 2023-04-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_alter_test_result_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams_collection',
            name='Is_split',
        ),
    ]
