# Generated by Django 4.1.6 on 2023-04-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0018_remove_exams_collection_is_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams_collection',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
